all:
	pdflatex report.tex

bib:
	pdflatex report.tex
	bibtex report
	pdflatex report.tex

bibtex:
	pdflatex report.tex
	bibtex report
	pdflatex report.tex

clean:
	rm -f report.aux report.log report.bbl report.blg report.out

