name: yolo2

dependencies:
  - python==3.7.13
  - pip
  - pip:
    - opencv-contrib-python
    - tensorflow==2.3.1
    - seaborn>=0.10.0
    - tqdm==4.60.0
    - pandas
    - awscli
    - urllib3
    - mss